src-git packages https://git.openwrt.org/feed/packages.git^0774799a271fc22724fae6f7ee32f5df932cc08a
src-git luci https://git.openwrt.org/project/luci.git^aa3d48836e90ae0706c8d8f9b46b8371e45cfe1f
src-link lt22m ../../lt22m-local-feed
